<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<WarningsNotAsErrors>NU1903</WarningsNotAsErrors>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="Api\Domain\Entities\Models\ConfiguracoesLoja\ConfiguracaoLoja.cs" />
	  <None Include="C:\Users\erick\source\repos\MenuFast.Api\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<None Update="credentials.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>

		<PackageReference Include="AutoMapper" Version="14.0.0" />

		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />

		<PackageReference Include="ClosedXML" Version="0.105.0" />

		<PackageReference Include="Dapper" Version="2.1.79" />

		<PackageReference Include="FluentValidation" Version="12.1.1" />

		<PackageReference Include="Google.Apis.Auth" Version="1.75.0" />

		<PackageReference Include="Google.Apis.Gmail.v1" Version="1.75.0.4225" />

		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />

		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />

		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />

		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />


		<!-- Entity Framework Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />

		<PackageReference Include="MimeKit" Version="4.17.0" />

		<PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />


		<PackageReference Include="QuestPDF" Version="2026.7.0" />


		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />


		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />


		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.10" />

		<PackageReference Include="StackExchange.Redis" Version="3.0.17" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />

	</ItemGroup>


	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Users\erick\source\repos\MenuFast.Api\.editorconfig" />
	</ItemGroup>


</Project>