// <auto-generated />
using System;
using MenuFast.Api.Api.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuFast.Api.Migrations
{
    [DbContext(typeof(MenuFastContext))]
    [Migration("20260809024845_AjsuteFuncionerio")]
    partial class AjsuteFuncionerio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComplementoProduto", b =>
                {
                    b.Property<int>("ComplementosId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("int");

                    b.HasKey("ComplementosId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("ComplementoProduto");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do cardápio.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se o cardápio está ativo.");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasComment("Data de cadastro do cardápio.");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descrição do cardápio.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do cardápio.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Cardapio", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da categoria de produtos.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se a categoria está ativa.");

                    b.Property<int>("CardapioId")
                        .HasColumnType("int")
                        .HasComment("Cardápio ao qual a categoria pertence.");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Descrição da categoria.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da categoria.");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasComment("Ordem de exibição da categoria no cardápio.");

                    b.HasKey("Id");

                    b.HasIndex("CardapioId");

                    b.HasIndex("LojaId");

                    b.ToTable("CategoriaProduto", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Complemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do complemento.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se o complemento está ativo.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do complemento.");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit")
                        .HasComment("Indica se o complemento é obrigatório.");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor adicional do complemento.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Complemento", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.OpcaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da opção do produto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<decimal>("Acrescimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor de acréscimo da opção.");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da opção do produto.");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasComment("Produto ao qual a opção pertence.");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("OpcaoProduto", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do produto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se o produto está ativo.");

                    b.Property<int>("CategoriaProdutoId")
                        .HasColumnType("int")
                        .HasComment("Categoria à qual o produto pertence.");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Código de barras do produto.");

                    b.Property<bool>("ControlaEstoque")
                        .HasColumnType("bit")
                        .HasComment("Indica se o produto controla estoque.");

                    b.Property<decimal>("Custo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Custo do produto.");

                    b.Property<string>("FotoProduto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Caminho ou URL da foto do produto.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do produto.");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Preço de venda do produto.");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.HasIndex("LojaId");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cliente.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do cliente.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se o cliente está ativo.");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Bairro do endereço.");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("CEP do endereço.");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasComment("CPF do cliente.");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Cidade do endereço.");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Complemento do endereço.");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasComment("Data de cadastro do cliente.");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasComment("Data de nascimento do cliente.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("E-mail do cliente.");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("UF do endereço.");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasComment("Latitude do endereço do cliente.");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Logradouro do endereço.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja à qual o cliente pertence.");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasComment("Longitude do endereço do cliente.");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Nome completo do cliente.");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número do endereço.");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Observações do cliente.");

                    b.Property<string>("PontoReferencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Ponto de referência do endereço.");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Telefone do cliente.");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("WhatsApp do cliente.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.ConfiguracaoLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da configuração do restaurante.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se a configuração está ativa.");

                    b.Property<bool>("CobraTaxaServico")
                        .HasColumnType("bit")
                        .HasComment("Indica se cobra taxa de serviço.");

                    b.Property<bool>("ControlaEstoque")
                        .HasColumnType("bit")
                        .HasComment("Indica se o restaurante utiliza controle de estoque.");

                    b.Property<bool>("EnviarPedidoAutomaticamenteBar")
                        .HasColumnType("bit")
                        .HasComment("Indica se o pedido deve ser enviado automaticamente para o bar.");

                    b.Property<bool>("EnviarPedidoAutomaticamenteCozinha")
                        .HasColumnType("bit")
                        .HasComment("Indica se o pedido deve ser enviado automaticamente para a cozinha.");

                    b.Property<bool>("ExigirGarcomNaMesa")
                        .HasColumnType("bit")
                        .HasComment("Indica se é obrigatório informar garçom responsável pela mesa.");

                    b.Property<bool>("ImprimirPedidoAutomaticamente")
                        .HasColumnType("bit")
                        .HasComment("Indica se o pedido deve ser impresso automaticamente.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja vinculada à configuração do restaurante.");

                    b.Property<decimal>("PercentualTaxaServico")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasComment("Percentual aplicado para cobrança da taxa de serviço.");

                    b.Property<bool>("PermiteVendaSemEstoque")
                        .HasColumnType("bit")
                        .HasComment("Indica se permite realizar venda de produtos sem estoque.");

                    b.Property<bool>("TrabalhaComDelivery")
                        .HasColumnType("bit")
                        .HasComment("Indica se o restaurante trabalha com pedidos delivery.");

                    b.Property<bool>("TrabalhaComMesa")
                        .HasColumnType("bit")
                        .HasComment("Indica se o restaurante trabalha com controle de mesas.");

                    b.Property<bool>("TrabalhaComRetirada")
                        .HasColumnType("bit")
                        .HasComment("Indica se o restaurante trabalha com retirada no balcão.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.ToTable("ConfiguracaoLoja", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da forma de pagamento.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se a forma de pagamento está ativa.");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Imagem ou ícone da forma de pagamento.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da forma de pagamento.");

                    b.Property<bool>("PermiteTroco")
                        .HasColumnType("bit")
                        .HasComment("Indica se a forma de pagamento permite troco.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("FormaPagamento", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.HorarioFuncionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do horário de funcionamento.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int")
                        .HasComment("Dia da semana em que o horário é aplicado.");

                    b.Property<bool>("Fechado")
                        .HasColumnType("bit")
                        .HasComment("Indica se o estabelecimento não funciona neste dia.");

                    b.Property<TimeSpan>("HoraAbertura")
                        .HasColumnType("time")
                        .HasComment("Horário de abertura do estabelecimento.");

                    b.Property<TimeSpan>("HoraFechamento")
                        .HasColumnType("time")
                        .HasComment("Horário de fechamento do estabelecimento.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja vinculada ao horário de funcionamento.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("HorarioFuncionamento", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cozinha.OrdemProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da ordem de produção.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de entrada da ordem na produção.");

                    b.Property<DateTime?>("FimPreparo")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de término do preparo.");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pela produção.");

                    b.Property<DateTime?>("InicioPreparo")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de início do preparo.");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Observações da ordem de produção.");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasComment("Pedido vinculado à ordem de produção.");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasComment("Prioridade da ordem de produção.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Status atual da ordem de produção.");

                    b.HasKey("Id");

                    b.ToTable("OrdemProducao", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do caixa.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L);

                    b.Property<bool>("Aberto")
                        .HasColumnType("bit")
                        .HasComment("Indica se o caixa está aberto.");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de abertura do caixa.");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de fechamento do caixa.");

                    b.Property<int>("FuncioanrioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pelo caixa.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome do caixa.");

                    b.Property<decimal>("ValorAbertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor informado na abertura do caixa.");

                    b.Property<decimal>("ValorFechamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor informado no fechamento do caixa.");

                    b.HasKey("Id");

                    b.HasIndex("FuncioanrioId");

                    b.HasIndex("LojaId");

                    b.ToTable("Caixa", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da conta a pagar.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 13001L);

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2")
                        .HasComment("Data de pagamento da conta.");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasComment("Data de vencimento da conta.");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Descrição da conta a pagar.");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja responsável pela conta a pagar.");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit")
                        .HasComment("Indica se a conta foi paga.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Status atual da conta financeira.");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor da conta a pagar.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("ContaPagar", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.ContaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da conta a receber.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 12001L);

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("datetime2")
                        .HasComment("Data de recebimento da conta.");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasComment("Data de vencimento da conta.");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Descrição da conta a receber.");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja responsável pela conta a receber.");

                    b.Property<bool>("Recebido")
                        .HasColumnType("bit")
                        .HasComment("Indica se a conta foi recebida.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Status atual da conta financeira.");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor da conta a receber.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("ContaReceber", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.MovimentoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do movimento de caixa.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 11001L);

                    b.Property<int>("CaixaId")
                        .HasColumnType("int")
                        .HasComment("Caixa vinculado ao movimento.");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora do movimento.");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Descrição do movimento.");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pelo movimento.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja vinculada ao movimento de caixa.");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Tipo do movimento realizado no caixa.");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor do movimento.");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.ToTable("MovimentoCaixa", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1000L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool?>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataBloqueio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpiracaoSenha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("int");

                    b.Property<bool>("PrimeiroAcesso")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TentativasLogin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LojaId");

                    b.HasIndex("PerfilId");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.ChavePix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da chave Pix.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Valor da chave Pix cadastrada.");

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("int")
                        .HasComment("Identificador da conta bancária vinculada à chave Pix.");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indica se esta é a chave Pix principal da conta bancária.");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Tipo da chave Pix: CPF, CNPJ, e-mail, telefone ou chave aleatória.");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId", "Chave")
                        .IsUnique();

                    b.ToTable("ChavePix", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da conta bancária.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número da agência.");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nome da instituição financeira.");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Número da conta bancária.");

                    b.Property<string>("Digito")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Dígito verificador da conta.");

                    b.Property<string>("DocumentoTitular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("CPF ou CNPJ do titular da conta.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja proprietária da conta bancária.");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nome do titular da conta.");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("ContaBancaria", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da empresa.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasComment("Indica se a empresa está ativa no sistema.");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Bairro da empresa.");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasComment("CEP do endereço da empresa.");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Cidade da empresa.");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasComment("CNPJ da empresa.");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Complemento do endereço.");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasComment("Data de cadastro da empresa.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("E-mail principal da empresa.");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Estado da empresa.");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL do perfil ou página da empresa no Facebook.");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Inscrição estadual da empresa.");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL do perfil da empresa no Instagram.");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Caminho ou URL da logomarca da empresa.");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Logradouro da empresa.");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Nome fantasia da empresa.");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número do endereço.");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Razão social da empresa.");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Site oficial da empresa.");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Slug único utilizado para identificar a empresa na URL.");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Telefone principal da empresa.");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("Sigla da unidade federativa.");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Número ou link do WhatsApp da empresa.");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Loja", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Mesa.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da mesa.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 7001L);

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Número ou identificação da mesa.");

                    b.Property<int>("StatusMesa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único da entrega.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 12001L);

                    b.Property<int?>("ClienteEnderecoId")
                        .HasColumnType("int")
                        .HasComment("Endereço do cliente para entrega.");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora da entrega realizada.");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora de saída para entrega.");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pela entrega.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja vinculada à entrega.");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasComment("Pedido vinculado à entrega.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Status atual da entrega.");

                    b.Property<decimal>("TaxaEntrega")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor da taxa de entrega.");

                    b.HasKey("Id");

                    b.HasIndex("ClienteEnderecoId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Entrega", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.HistoricoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do histórico do pedido.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 4001L);

                    b.Property<int>("Acao")
                        .HasColumnType("int")
                        .HasComment("Ação realizada no histórico do pedido.");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora do registro do histórico.");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pela ação.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int")
                        .HasComment("Loja vinculada ao histórico do pedido.");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Observação do histórico.");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasComment("Pedido relacionado ao histórico.");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasComment("Usuário responsável pela ação.");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("HistoricoPedido", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do item do pedido.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 3001L);

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Desconto aplicado no item.");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Observação do item do pedido.");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasComment("Pedido vinculado ao item.");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasComment("Produto vinculado ao item.");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasComment("Quantidade do produto no pedido.");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor total do item.");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor unitário do produto.");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItemPedido", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.PagamentoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do pagamento do pedido.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 2001L);

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora do pagamento.");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int")
                        .HasComment("Forma de pagamento utilizada.");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int")
                        .HasComment("Pedido vinculado ao pagamento.");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor pago.");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PagamentoPedido", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identificador único do pedido.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L, 10);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasComment("Cliente vinculado ao pedido.");

                    b.Property<DateTime>("DataPedidoHora")
                        .HasColumnType("datetime2")
                        .HasComment("Data e hora da criação do pedido.");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor de desconto aplicado.");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int")
                        .HasComment("Funcionário responsável pelo pedido.");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int")
                        .HasComment("Mesa vinculada ao pedido.");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Observações do pedido.");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Status atual do pedido.");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor subtotal dos itens do pedido.");

                    b.Property<decimal>("TaxaEntrega")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Taxa de entrega aplicada.");

                    b.Property<decimal>("TaxaServico")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Taxa de serviço aplicada.");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("int")
                        .HasComment("Tipo do pedido realizado.");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Valor total do pedido.");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.HasIndex("MesaId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.ConfiguracaoSeguranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("MaxTentativasLogin")
                        .HasColumnType("int");

                    b.Property<int>("TempoBloqueioMinutos")
                        .HasColumnType("int");

                    b.Property<int>("TempoExpiracaoSessaoDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.ToTable("ConfiguracaoSeguranca", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.HistoricoAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLogout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<bool>("SessaoAtiva")
                        .HasColumnType("bit");

                    b.Property<int>("TipoAcesso")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("LojaId");

                    b.ToTable("HistoricoAcessos", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.PerfilPermissao", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissao", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissao", (string)null);
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.TemplateEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LojaId");

                    b.ToTable("TemplatesEmail");
                });

            modelBuilder.Entity("ComplementoProduto", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Complemento", null)
                        .WithMany()
                        .HasForeignKey("ComplementosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Cardapio", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.CategoriaProduto", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Cardapio", "Cardapio")
                        .WithMany("Categorias")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cardapio");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Complemento", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.OpcaoProduto", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Produto", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.CategoriaProduto", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cliente.Cliente", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.ConfiguracaoLoja", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithOne("Configuracao")
                        .HasForeignKey("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.ConfiguracaoLoja", "LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.FormaPagamento", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.HorarioFuncionamento", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany("Horarios")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.Caixa", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncioanrioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.ContaPagar", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.ContaReceber", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.MovimentoCaixa", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.Caixa", "Caixa")
                        .WithMany("Movimentos")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Caixa");

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Loja");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.ChavePix", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.ContaBancaria", "ContaBancaria")
                        .WithMany("ChavesPix")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.ContaBancaria", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Mesa.Mesa", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Entrega", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Cliente.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteEnderecoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", "Pedido")
                        .WithOne("Entrega")
                        .HasForeignKey("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Entrega", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.HistoricoPedido", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.ItemPedido", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.PagamentoPedido", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.ConfiguracoesLoja.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Mesa.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.ConfiguracaoSeguranca", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithOne()
                        .HasForeignKey("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.ConfiguracaoSeguranca", "LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.HistoricoAcesso", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.PerfilPermissao", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.TemplateEmail", b =>
                {
                    b.HasOne("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.Cardapio", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Cardapio.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Financeiro.Caixa", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Funcionario.Perfil", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.ContaBancaria", b =>
                {
                    b.Navigation("ChavesPix");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Loja.Loja", b =>
                {
                    b.Navigation("Configuracao");

                    b.Navigation("ContasBancarias");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Mesa.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Pedido.Pedido", b =>
                {
                    b.Navigation("Entrega");

                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("MenuFast.Api.Api.Domain.Entities.Models.Seguranca.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
